# CONFIGURAÇÃO DO SITE
site_name: AcessAí
site_url: https://unbihc2025-1.github.io/IHC-2025.1-Grupo02/
use_directory_urls: false

# NAVEGAÇÃO
nav:
  - 'Início': 'index.md'
  
  - 'Desenvolvimento Web':
    - 'Desenvolvimento': 'devWeb/Desenvolvimento.md'
    
  - 'Design':
    - 'Princípios de Design': 'design/design.md'
    
  - 'Geração de Conteúdo':
    - 'Diretrizes de Conteúdo': 'geracaoConteudo/conteudo.md'
    
  - 'Gestão de Projetos':
    - 'Metodologia': 'gestaoProjeto/gestaoProjeto.md'
    
  - 'Ferramentas':
    - 'Ferramentas de Acessibilidade': 'tools/ferramentas.md'
    - 'Heurísticas de Nielsen': 'tools/heuristicas.md'
    

# TEMA
theme:
  name: material
  palette:
    scheme: default
    primary: 'red'
    accent: 'red'
  locale: pt_BR
  logo: imagens/Acessaí.png
  favicon: imagens/Acessaí.png

# EXTENSÕES MARKDOWN
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

extra_css:
  - css/extra.css # Caminho para o seu arquivo CSS personalizado

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js
  - js/main.js # Seu JavaScript personalizado
