# CONFIGURAÇÃO DO SITE
site_name: AcessAí
site_url: https://unbihc2025-1.github.io/IHC-2025.1-Grupo02/
use_directory_urls: false

# NAVEGAÇÃO
nav:
  - 'Início': 'index.md'
  - 'Desenvolvimento Web':
    - 'Conteúdo não textual': 'devWeb/non_text_content.md'
  - 'Design':
    - 'Princípios de Design': 'design/design.md'
  - 'Geração de Conteúdo':
    - 'Diretrizes de Conteúdo': 'geracaoConteudo/conteudo.md'
  - 'Gestão de Projetos':
    - 'Metodologia': 'gestaoProjeto/gestaoProjeto.md'
  - 'Ferramentas':
    - 'Ferramentas de Acessibilidade': 'tools/ferramentas.md'

# TEMA
theme:
  name: readthedocs
  locale: pt_BR
  logo: imagens/Acessaí.png
  favicon: imagens/Acessaí.png

# EXTENSÕES MARKDOWN
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

# CSS EXTRA
extra_css:
  - stylesheets/extra.css
