# Nome do robô, que aparecerá na aba "Actions" do GitHub
name: Publicar Documentação no GitHub Pages

# Gatilho: Quando o robô deve agir?
on:
  push:
    branches:
      - main

# Permissões: Dê ao robô permissão para escrever no repositório
permissions:
  contents: write

# Tarefas: O que o robô deve fazer?
jobs:
  publicar-site:
    # O tipo de máquina que o robô usará
    runs-on: ubuntu-latest

    # O passo-a-passo que o robô seguirá
    steps:
      # Passo 1: Baixar o código do seu repositório
      - name: Baixar o código
        uses: actions/checkout@v4

      # Passo 2: Configurar o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Passo 3: Instalar as dependências
      - name: Instalar dependências
        run: pip install mkdocs pymdown-extensions

      # Passo 4: Rodar o comando de publicação
      - name: Publicar site com MkDocs
        run: mkdocs gh-deploy --force